### ISSUE TITLE
What happened to Bili2.0?

### ISSUE THREAD

**Issue by Sh4wnC** [yjqiang/Feedback#2]

**Comment by yjqiang** [comment]
Nothing, just in case.

**Comment by yjqiang** [comment]
U have the access to bili2.0 now, after accepting the invitation.

**Comment by zuosc** [comment]
> U have the access to bili2.0 now, after accepting the invitation.

带带我

**Comment by yjqiang** [comment]
> > U have the access to bili2.0 now, after accepting the invitation.
> 
> 带带我

DONE

**Comment by JerryRich** [comment]
求带

**Comment by yjqiang** [comment]
@JerryRich DONE
