### ISSUE TITLE
bili2.0重新公开，并且决定不发生特殊情况下永久公开

### ISSUE THREAD

**Issue by KNulL0** [yjqiang/Feedback#3]

**Comment by pjy612** [comment]
QAQ

**Comment by D3ee** [comment]
我明示了，你懂的

**Comment by handsomebubu** [comment]
YJ  我想进私有2.0

**Comment by yjqiang** [comment]
@handsomebubu @D3ee DONE

**Comment by HDXP** [comment]
求带QAQ

**Comment by Cartagra** [comment]
求上车2.0

**Comment by yjqiang** [comment]
@HDXP @Cartagra DONE

**Comment by dantesawake** [comment]
QAQ大佬求带

**Comment by yjqiang** [comment]
@dantesawake DONE

**Comment by StarryFK** [comment]
__请求使用私有项目，感谢dalao__

**Comment by rabbit2rabbit** [comment]
emmmmm屁股拜托你了，请轻一点

**Comment by wwh1004** [comment]
大佬带带我

**Comment by yjqiang** [comment]
@StarryFK @rabbit2rabbit @wwh1004 DONE

**Comment by nekoprpr** [comment]
@yjqiang 大佬带带我!!!

**Comment by AdiEcho** [comment]
请求使用私有项目，感谢dalao

**Comment by HDXP** [comment]
大佬我没收到私有请求，能不能重新拉一下，非常感谢QAQ

**Comment by yjqiang** [comment]
@HDXP @AdiEcho DOEN

**Comment by nekoprpr** [comment]
@yjqiang 大佬大佬 怎么跳过我了

**Comment by yjqiang** [comment]
@nekoprpr DONE

**Comment by NAGATOYUKl** [comment]
请求加入QwQ 我什么都会做的！( 感谢(･ω･)ﾉ

**Comment by wangmanv2** [comment]
求大佬带飞 嘤嘤嘤

**Comment by yjqiang** [comment]
@wangmanv2 @NAGATOYUKl DONE

**Comment by YCCCCCCCCC** [comment]
@yjqiang 请求使用私有项目，感谢大佬~

**Comment by Lex573** [comment]
1

**Comment by yjqiang** [comment]
@Lex573 DONE

**Comment by qq1341563002** [comment]
@yjqiang 请求使用私有项目，感谢感谢

**Comment by yjqiang** [comment]
@qq1341563002 DONE

**Comment by Xeliee** [comment]
跪求大佬带飞！！

**Comment by yjqiang** [comment]
@Xeliee DONE

**Comment by Muromi-Rikka** [comment]
1. 求带飞！

**Comment by qwasddd** [comment]
bili2.0是要有贡献才能进的吗

**Comment by yainse** [comment]
大佬求带..

**Comment by Sakatagintoki53** [comment]
大佬求带，谢谢

**Comment by yjqiang** [comment]
@Muromi-Rikka @qwasddd @yainse @Sakatagintoki53 DONE

**Comment by CuteLeaf** [comment]
申请项目权限

**Comment by jjnnnh** [comment]
@yjqiang 大佬，我想对下，自用，谢谢

**Comment by yjqiang** [comment]
@Summmm @jjnnnh DONE

**Comment by rabbit-cat** [comment]
@yjqiang 大佬，申请下项目权限，自用，谢谢

**Comment by heatded** [comment]
@yjqiang 大佬大佬，带我一个，自用，非常感谢

**Comment by colorsakura** [comment]
申请加入

**Comment by chy89224** [comment]
大佬，申请下项目权限，自用，十分感谢

**Comment by PussAzuki** [comment]
@yjqiang 请求进入私有仓库，如果可以的话，谢谢大佬（

**Comment by ATKghost** [comment]
@yjqiang  申请bili2.0使用权限，感谢大佬的付出！

**Comment by cznqkjf12138** [comment]
求大佬带飞

**Comment by misakamikoton** [comment]
@yjqiang 申请bili2.0权限，仅搭建自用，谢谢大佬

**Comment by yjqiang** [comment]
@rabbit-cat @heatded @colorsakura @chy89224 @PussAzuki @ATKghost @cznqkjf12138 @Lirici DONE

**Comment by LetMeDecay** [comment]
同样申请一下，准备更新发现竟然没了

**Comment by heicat1337** [comment]
申请一下QAQ

**Comment by kkigws** [comment]
申请使用权限，自用，感谢~

**Comment by shkey** [comment]
@yjqiang 同求加入bili2.0

**Comment by yjqiang** [comment]
@DkWyatt @xiaozouwwwwww @kkigws @shkey DONE

**Comment by mymzd** [comment]
@yjqiang 求加入bili2.0，想接着挂机

**Comment by Kjcdkcnjji** [comment]
请求加入 感谢您

**Comment by Mrsin-x** [comment]
申请加入~

**Comment by nalomu** [comment]
申请自用，大佬求带

**Comment by Jutean** [comment]
申请自用且保密，愿意付费。

**Comment by yjqiang** [comment]
@mymzd @Kjcdkcnjji @Mrsinss @nalomu @Jutean DONE

**Comment by mantislin** [comment]
申请自用并且保密，大佬求带啊啊啊啊～

**Comment by slinar** [comment]
PY一波私有bili2.0 自用 ←◡←

**Comment by 997sama** [comment]
哇，dalao带带我=-=我保证自用，发4

**Comment by yjqiang** [comment]
@slinar @997sama @mantislin reopen

**Comment by AC12138** [comment]
申请bili2.0使用权限，感谢大佬！！！！！

**Comment by yjqiang** [comment]
@AC12138 已经重新公开了，不需要权限

**Comment by AC12138** [comment]
> @AC12138 已经重新公开了，不需要权限

看到了，谢谢大佬！

**Comment by mantislin** [comment]
> 
> 
> @slinar @997sama @mantislin reopen

谢！

**Comment by 8MiYile** [comment]
请求使用私有项目，用于自身的大批量养号

**Comment by versacehy** [comment]
申请bili2.0使用权限，感谢大佬！！！！！

**Comment by yjqiang** [comment]
@versacehy 已经公开了  所有人都可以使用
