### ISSUE TITLE
是否可以搬运bilibili-live-tools到其他论坛？

### ISSUE THREAD

**Issue by AC12138** [yjqiang/Feedback#9]
RT，之前在52破解论坛看到一个帖子，是关于大大您的这个bilibili-live-tools的，但是那个人将您的东西作为那个人的原创，前几天帖子就被删了，我看人气还蛮高的，能否搬运呢？

**Comment by yjqiang** [comment]
可以

**Comment by AC12138** [comment]
非常感谢！
